// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetworkServer.SocNetworkDBContext;

#nullable disable

namespace SocialNetworkServer.Migrations
{
    [DbContext(typeof(SocialNetworkDBContext))]
    [Migration("20240317193011_alpha_migration_0_1")]
    partial class alpha_migration_0_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("PageId");

                    b.ToTable("Pages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Page");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PostId");

                    b.HasIndex("PageId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PageId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserAccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.CommunityPage", b =>
                {
                    b.HasBaseType("SocialNetworkServer.SocNetworkDBContext.Entities.Page");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thematics")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("UserAccountId");

                    b.HasDiscriminator().HasValue("CommunityPage");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.UserPage", b =>
                {
                    b.HasBaseType("SocialNetworkServer.SocNetworkDBContext.Entities.Page");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("New");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("User");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_Pages_UserAccountId1");

                    b.HasDiscriminator().HasValue("UserPage");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Post", b =>
                {
                    b.HasOne("SocialNetworkServer.SocNetworkDBContext.Entities.Page", "Page")
                        .WithMany("Posts")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Subscription", b =>
                {
                    b.HasOne("SocialNetworkServer.SocNetworkDBContext.Entities.Page", "Page")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialNetworkServer.SocNetworkDBContext.Entities.UserPage", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.CommunityPage", b =>
                {
                    b.HasOne("SocialNetworkServer.SocNetworkDBContext.Entities.UserAccount", "UserAccount")
                        .WithMany("Communities")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.UserPage", b =>
                {
                    b.HasOne("SocialNetworkServer.SocNetworkDBContext.Entities.UserAccount", "UserAccount")
                        .WithOne("UserPage")
                        .HasForeignKey("SocialNetworkServer.SocNetworkDBContext.Entities.UserPage", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pages_Accounts_UserAccountId1");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.Page", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SocialNetworkServer.SocNetworkDBContext.Entities.UserAccount", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("UserPage")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
